import type { DomainKey } from "./types";

/**
 * Ascendant-sign-flavored color for each domain — the same convention
 * classical "life predictions" writing uses (your rising sign colors
 * your outward approach to each area of life). Original wording,
 * written for this app; not sourced from any third-party report.
 */
export const FLAVOR_TEXT: Record<DomainKey, Record<string, string>> = {
  character: {
    Aries: "You lead with instinct and courage, often acting before you've fully thought things through. Directness is your gift — just remember that not everyone moves at your pace.",
    Taurus: "You're steady, patient, and quietly stubborn, valuing comfort and consistency over sudden change. Once you commit to something, you rarely let go.",
    Gemini: "Curious and quick-witted, you juggle many interests and conversations with ease. Restlessness is your shadow — depth comes when you choose to stay with one thing longer.",
    Cancer: "You feel everything deeply and protect the people you love fiercely. Moods can pull you inward, but that same sensitivity makes you remarkably intuitive.",
    Leo: "Warm, expressive, and naturally magnetic, you like being seen and you like others to shine too. Pride can sting when it's wounded, but your generosity usually wins out.",
    Virgo: "You notice what others miss and hold yourself to a high standard, sometimes too high. Practical and modest, you'd rather be useful than admired.",
    Libra: "You seek balance and fairness in nearly everything, and you read a room before you speak. Indecision creeps in when every option looks equally reasonable.",
    Scorpio: "Intense and private, you feel things at full volume even when your face gives nothing away. Once trust is broken it's hard to earn back, but loyalty runs deep.",
    Sagittarius: "Optimistic and freedom-loving, you'd rather chase a horizon than settle into routine. Bluntness is your honesty showing through — tact takes practice.",
    Capricorn: "Disciplined and quietly ambitious, you measure progress in years, not days. You can be hard on yourself, but that same rigor earns you real, lasting respect.",
    Aquarius: "Independent and a little unconventional, you think in systems and ideals rather than small talk. Detachment protects you, though it can read as distance to others.",
    Pisces: "Imaginative and compassionate, you absorb the moods of everyone around you. Boundaries are your growth edge — without them, your empathy can exhaust you.",
  },
  happiness: {
    Aries: "Fulfillment comes when you're moving toward something — a stalled goal is what unsettles you fastest. A little stillness each day keeps that drive from turning into restlessness.",
    Taurus: "You find contentment in the tangible: a comfortable home, good food, familiar faces. Security matters more to you than excitement, and there's real wisdom in that.",
    Gemini: "You feel most alive when learning something new or talking it through with someone. Contentment can feel elusive simply because your mind rarely sits still.",
    Cancer: "Home and family are where your happiness is rooted, and you measure a good life by how safe the people around you feel. Old memories can pull at you more than you let on.",
    Leo: "Being appreciated for who you genuinely are — not just admired from a distance — is what fulfills you. Applause is nice, but warmth is what you're actually after.",
    Virgo: "You feel settled when things are in order and you're genuinely useful to someone. Perfectionism can quietly rob you of the satisfaction you've already earned.",
    Libra: "Harmony in your closest relationships is the surest measure of your happiness. When you stop over-adjusting for others, contentment tends to arrive on its own.",
    Scorpio: "You find peace only once you've gone beneath the surface of something — small talk rarely satisfies you. Letting go of old hurts, more than acquiring anything new, is your path to ease.",
    Sagittarius: "New places, new ideas, new possibilities — that's where your joy lives. Contentment grows once you realize the search itself can be the reward.",
    Capricorn: "Fulfillment, for you, is earned — a milestone reached after real effort means more than anything handed to you. Learning to enjoy the climb, not just the summit, brings more peace.",
    Aquarius: "You feel fulfilled contributing to something larger than yourself, an idea or a community you believe in. Connection on your own terms matters more to you than convention.",
    Pisces: "Quiet, unstructured time — music, art, water, dreams — restores you more than achievement does. Grounding those feelings in something real keeps contentment from drifting away.",
  },
  lifestyle: {
    Aries: "Your days run best with a clear target and a bit of urgency — you're not built for a slow, meandering routine. Physical activity keeps your energy from turning into impatience.",
    Taurus: "You prefer a life with predictable rhythms: the same coffee, the same walk, the same comforts. Change unsettles you less when it's introduced slowly.",
    Gemini: "Variety keeps your days interesting — different people, different tasks, different scenery. A rigid schedule feels like a cage unless there's room to improvise.",
    Cancer: "Your routines revolve around the people you care for, and your mood often sets the tone for the whole household. A private ritual to reset each day serves you well.",
    Leo: "You like your days to have a little flair — good company, a bit of style, something worth showing up for. Recognition, even small, keeps your motivation warm.",
    Virgo: "You function best with a system: lists, routines, a sense of order behind the scenes. Leave a little room for spontaneity so the system doesn't become a cage.",
    Libra: "Your lifestyle bends around the people you share it with — plans firm up once you know who else is involved. Time alone to simply decide what you want is worth protecting.",
    Scorpio: "You prefer depth over breadth even in daily life — fewer commitments, held more intensely. Guard some time for rest; your intensity can quietly run you down.",
    Sagittarius: "Your ideal day has room for the unplanned — a spontaneous trip, an unscheduled conversation. Too much structure can make you feel boxed in.",
    Capricorn: "Your days are organized around long-term goals, even the small ones. Building in genuine rest, not just downtime between tasks, is worth the effort.",
    Aquarius: "You like a lifestyle that leaves room for your own ideas and causes, even if it looks unconventional to others. Too much routine dulls your spark.",
    Pisces: "Your days flow more than they're scheduled, and you do your best work when you're not forced into someone else's timetable. A little structure protects you from drifting.",
  },
  career: {
    Aries: "You do best leading rather than following, and careers with a clear finish line suit you well. Impatience with slow institutions can push you toward founding your own path.",
    Taurus: "You build a career the way you build most things — steadily, and built to last. Recognition comes later than you'd like, but it tends to be durable once it arrives.",
    Gemini: "A career that lets you talk, write, sell, or teach plays directly to your strengths. Boredom is the real risk — variety within the role matters more to you than the title.",
    Cancer: "You thrive in work that feels like it's caring for something — people, a team, a legacy. Job security matters to you more than most, and that instinct usually serves you well.",
    Leo: "You rise fastest in roles where your work is visible and your name is attached to it. Leadership suits you naturally, provided you share the spotlight when it's earned.",
    Virgo: "Precision and reliability make you the person a team quietly can't function without. Your challenge is claiming credit for work you'd rather just get right.",
    Libra: "You do well in careers built on negotiation, diplomacy, or aesthetics — anywhere fairness and taste matter. Partnerships, formal or informal, tend to accelerate your progress.",
    Scorpio: "You're drawn to careers with real stakes — research, strategy, transformation, crisis work. Trust, once given professionally, becomes a genuine competitive advantage for you.",
    Sagittarius: "Careers with travel, teaching, or big-picture thinking hold your attention longest. A desk job with no room to explore will wear on you faster than the workload itself.",
    Capricorn: "You're built for the long climb, and authority tends to come to you with time and consistency. Few signs are more naturally suited to eventually running the show.",
    Aquarius: "You do best in work tied to an idea or a cause bigger than a paycheck — innovation, technology, reform. Conventional hierarchies fit you less well than independent or expert roles.",
    Pisces: "Creative, healing, or spiritually-oriented work tends to fulfill you far more than purely commercial paths. Structure from a good mentor or partner helps your talent actually land somewhere.",
  },
  occupation: {
    Aries: "You need work with visible progress and a bit of competition — sales, sport, emergency response, or anything with a scoreboard suits your temperament.",
    Taurus: "Hands-on, tangible work — finance, land, food, craft, or anything you can build and hold — tends to satisfy you more than abstract or fast-moving fields.",
    Gemini: "Communication-heavy occupations — media, marketing, translation, teaching — fit your quick mind, especially roles that mix several small tasks rather than one long one.",
    Cancer: "Caregiving, hospitality, real estate, or anything rooted in home and family naturally draws you, since you work best when the outcome feels personal.",
    Leo: "Performance, leadership, entertainment, or client-facing roles let your natural presence do real work — you rarely thrive fully behind the scenes.",
    Virgo: "Detail-driven fields — healthcare, editing, accounting, quality control — reward the precision you bring almost without trying.",
    Libra: "Law, design, counseling, or diplomacy suit your instinct for balance and your genuine ease with people who disagree.",
    Scorpio: "Investigation, psychology, surgery, finance, or crisis management appeal to your appetite for what's hidden beneath the surface.",
    Sagittarius: "Travel, publishing, higher education, or international work matches your need for a wider horizon than most jobs offer.",
    Capricorn: "Management, government, engineering, or any field with a clear ladder rewards the patience and structure you naturally bring to work.",
    Aquarius: "Technology, science, activism, or anything genuinely inventive suits you better than a role defined entirely by someone else's rulebook.",
    Pisces: "Art, music, healing professions, or spiritual and charitable work let your sensitivity become a genuine professional strength rather than a liability.",
  },
  health: {
    Aries: "Your energy runs hot and fast, which is an asset until it burns out — headaches and minor injuries from rushing are your most likely stumbling blocks. Regular physical outlets keep that fire from turning inward.",
    Taurus: "You have solid, steady stamina, though comfort-seeking can tip into overindulgence — the throat and neck are worth paying attention to. Consistent movement matters more for you than intense but occasional exercise.",
    Gemini: "Your health is closely tied to your mental state — nervous energy and restlessness show up in the body before you notice them elsewhere. Rest for the mind is often the actual remedy your body is asking for.",
    Cancer: "You're sensitive to stress in a very physical way, often through digestion or disrupted sleep. Emotional processing, not just rest, is part of your genuine self-care.",
    Leo: "You generally carry good vitality, with the heart and upper back as areas worth minding, especially under prolonged stress. Recognition and joy are, quite literally, good for your health.",
    Virgo: "You're prone to worry that settles in the stomach, and you notice symptoms earlier than most people. A less perfectionistic relationship with your own routines will serve you as well as any diet.",
    Libra: "Balance is your health theme in every sense — the kidneys and lower back can flag when your life tips too far out of equilibrium. Relationships that drain you affect your body more than you'd expect.",
    Scorpio: "You have real resilience and recover from setbacks others wouldn't, though old emotional weight can manifest physically if it's never released. Regular, honest processing of stress is protective for you.",
    Sagittarius: "Your vitality is generally strong, with hips and thighs the area to watch, especially from overexertion or travel fatigue. Moderation is a harder lesson for you than most, but a worthwhile one.",
    Capricorn: "You're durable but prone to pushing through when you should rest — bones, joints, and teeth are worth long-term attention. Consistent care now pays off disproportionately later in life.",
    Aquarius: "Your health runs in cycles tied to circulation and nervous tension, often worsened by irregular routines. A steadier daily rhythm helps more than any single remedy.",
    Pisces: "You're sensitive to your environment and to others' moods in ways that show up physically, especially through the feet and immune resilience. Enough solitude and sleep is not indulgence for you — it's maintenance.",
  },
  hobbies: {
    Aries: "Competitive sport, adventure activities, or anything with a clear physical challenge genuinely recharges you rather than tiring you out.",
    Taurus: "Gardening, cooking, music, or working with your hands gives you the tactile, unhurried pleasure you're drawn to.",
    Gemini: "Puzzles, reading, games, and hobbies that involve other people or constant novelty hold your attention best.",
    Cancer: "Cooking, collecting, photography, or anything tied to memory and home lets you unwind on your own terms.",
    Leo: "Performance-adjacent hobbies — theatre, dance, hosting, creative arts — let you enjoy being seen without any professional pressure attached.",
    Virgo: "Craft, fitness routines, and detail-oriented hobbies like model-building or fine cooking suit your love of getting things exactly right.",
    Libra: "Art, design, social sport, or anything aesthetically pleasing and shared with others is where you unwind best.",
    Scorpio: "Mysteries, research rabbit holes, intense sport, or anything with real depth appeals to you far more than casual pastimes.",
    Sagittarius: "Travel, outdoor adventure, and anything philosophical or exploratory is less a hobby for you than a genuine need.",
    Capricorn: "Structured hobbies with a visible skill ladder — an instrument, a sport, a serious craft — satisfy your instinct to always be improving.",
    Aquarius: "Unconventional hobbies, tech tinkering, or group causes suit you better than anything mainstream or purely decorative.",
    Pisces: "Music, art, film, and anything imaginative or water-adjacent offer you a genuine escape valve you shouldn't feel guilty using.",
  },
  love: {
    Aries: "You fall fast and pursue what you want directly, which is refreshing to some partners and overwhelming to others. Patience during the quieter stretches of a relationship is your real growth area.",
    Taurus: "You love slowly but completely, and once committed you're remarkably loyal. Possessiveness can creep in when you feel insecure — reassurance, not control, is what actually helps.",
    Gemini: "You need a partner who can hold a real conversation as much as a romantic one — mental connection is non-negotiable for you. Consistency is your growth edge more than passion.",
    Cancer: "You love by caring for someone in tangible ways, and you take relationships seriously even when you're guarded at first. Old wounds can make you overprotective — trust is worth extending in small doses.",
    Leo: "You love generously and expect to be admired in return, which is fair as long as it's mutual. Genuine partnership, not just devotion, is what keeps a relationship with you healthy.",
    Virgo: "You show love through small, practical acts of care more than grand gestures. Try not to let a habit of noticing flaws — in yourself or a partner — overshadow what's actually going well.",
    Libra: "Partnership itself matters deeply to you — you're genuinely happier paired than alone. Just be sure you're choosing a partner, not simply avoiding the discomfort of choosing.",
    Scorpio: "You love with total intensity and expect the same in return; anything shallow won't hold your interest. Jealousy is the shadow side of that depth, worth naming honestly when it appears.",
    Sagittarius: "You need a partner who gives you room to roam, literally or figuratively — a relationship that feels like a cage won't last. Honesty, sometimes blunt, is how you actually show commitment.",
    Capricorn: "You take love seriously and build it the way you build a career — with intention and long-term thinking. Vulnerability doesn't come easily, but it's what actually deepens the bond.",
    Aquarius: "You love as an equal and need a partner who respects your independence as much as your affection. Emotional distance can read as coldness even when it isn't — naming your feelings out loud helps.",
    Pisces: "You love with deep empathy and can lose yourself in a partner's world. Keeping a sense of your own identity alongside the relationship protects you from later resentment.",
  },
  finance: {
    Aries: "Money tends to come and go quickly for you — you earn assertively but spend just as fast on whatever excites you now. A simple rule of paying your future self first goes a long way.",
    Taurus: "You have a natural instinct for accumulating steady wealth and genuinely enjoy the security it brings. Your risk is being too cautious to ever invest what you've carefully saved.",
    Gemini: "You're likely to have more than one income stream at once, which suits your restless mind but can scatter your financial focus. A single, simple tracking habit prevents money from quietly slipping away.",
    Cancer: "You save with a purpose — usually home, family, or security — and feel genuinely uneasy without a cushion. Mixing money and emotion, especially with family, is worth watching.",
    Leo: "You spend generously, sometimes to keep up appearances, and enjoy earning in ways that also earn recognition. Budgeting for the occasional splurge keeps it from undermining your bigger goals.",
    Virgo: "You're naturally careful with money and genuinely good at managing details others overlook. The risk is being so cautious that you miss reasonable opportunities to grow what you have.",
    Libra: "You do well financially through partnerships and collaboration, though a taste for beautiful things can quietly strain a budget. A joint plan with a partner tends to work better for you than going it alone.",
    Scorpio: "You have sharp financial instincts and often do well with other people's money as well as your own — investing and strategy suit you. Secrecy about finances, even from a partner, tends to cause more problems than it solves.",
    Sagittarius: "Money flows toward opportunities and experiences for you, especially travel and education, but rarely stays put for long. A modest emergency fund protects your optimism from becoming a liability.",
    Capricorn: "You build wealth patiently and take financial responsibility seriously, often supporting others along the way. Few signs are as naturally suited to long-term financial security as you.",
    Aquarius: "Your income is often tied to unconventional or forward-thinking work, and you're generous with causes you believe in. A little structure keeps your generosity from outpacing your actual means.",
    Pisces: "You're generous, sometimes to a fault, and money matters can slip out of focus when your attention is elsewhere. A trusted person or simple system to manage the practical side genuinely frees you up.",
  },
  education: {
    Aries: "You learn best by doing rather than reading about it, and you lose patience with slow-paced instruction. A subject that lets you compete or move quickly holds your attention far longer.",
    Taurus: "You learn steadily and retain what you learn for a long time, though you resist being rushed. Practical, tangible subjects appeal to you more than abstract theory.",
    Gemini: "You're a naturally quick learner across many subjects at once, though depth can suffer if nothing forces you to slow down. Discussion and debate genuinely help you understand something better.",
    Cancer: "You learn best in an emotionally safe environment, with a mentor or subject you feel personally connected to. Nostalgia and history often appeal to you more than purely abstract subjects.",
    Leo: "You learn best when your effort is recognized — praise genuinely improves your performance, not just your mood. Subjects with a creative or performative angle come easiest to you.",
    Virgo: "You're a careful, methodical learner who genuinely enjoys mastering detail. Perfectionism can slow you down more than the material itself does.",
    Libra: "You learn well in collaboration and enjoy subjects with a social or aesthetic dimension — humanities and the arts often suit you more than isolated technical study.",
    Scorpio: "You learn best when a subject has real depth to uncover, and surface-level material bores you quickly. Research and investigation genuinely energize your studying.",
    Sagittarius: "You're drawn to big-picture subjects — philosophy, geography, foreign languages — more than narrow technical detail. Formal structure can feel limiting; independent study often suits you better.",
    Capricorn: "You approach learning with real discipline and long-term goals in mind, rarely studying just for its own sake. That patience tends to pay off in eventual mastery.",
    Aquarius: "You learn well independently and are drawn to unconventional or forward-looking subjects — science, technology, social theory. Rigid, traditional teaching methods can frustrate you more than the material itself.",
    Pisces: "You learn best through imagination and association rather than rote memorization, and creative or artistic subjects come easiest. A structured routine around study time helps your focus more than any particular technique.",
  },
};
